In [1]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading https://files.pythonhosted.org/packages/78/cb/faf0cb7fdc02e209b8391f669995398e877774a628dbad49a19016a4be5b/mysql_connector_python-8.0.22-cp37-cp37m-win_amd64.whl (842kB)
Collecting protobuf>=3.0.0 (from mysql-connector-python)
  Downloading https://files.pythonhosted.org/packages/1d/f4/089025cfa3ee62f89cae73f4d36daf46f339c6df61becfe4b24f3aeb3c0d/protobuf-3.14.0-cp37-cp37m-win_amd64.whl (798kB)
Requirement already satisfied: six>=1.9 in c:\users\kaise\anaconda3\lib\site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.12.0)
Installing collected packages: protobuf, mysql-connector-python
Successfully installed mysql-connector-python-8.0.22 protobuf-3.14.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import requests
import mysql
from mysql.connector import Error
from mysql.connector import errorcode

<h1>Genres einfügen</h1>

In [2]:
def insertGenres(insert_id, insert_name):
    try:
        connection = mysql.connector.connect(host='localhost',
                                             database='uniprojekt',
                                             user='root',
                                             password='')
        cursor = connection.cursor()
        
        mySql_insert_query = """INSERT INTO Genres (ID, Name) 
                                VALUES 
                                (%s, %s) """
        
        recordTuple = (insert_id, insert_name)
        
        cursor.execute(mySql_insert_query, recordTuple)
        connection.commit()
        print(cursor.rowcount, "Record inserted successfully into Series table")
        cursor.close()

    except mysql.connector.Error as error:
        print("Failed to insert record into Genres table {}".format(error))

    finally:
        if (connection.is_connected()):
            connection.close()
            print("MySQL connection is closed")

In [3]:
response_genre = requests.get("https://api.themoviedb.org/3/genre/tv/list?api_key=6896b525add50bf2605cbd1ecb2d95c9&language=de")
genres = response_genre.json()['genres']

genre_id = []
genre_name = []

for line in genres:
    genre_id.append(line['id'])
    genre_name.append(line['name'])

countOfGenres = len(genre_id)

counter = 0
while counter < countOfGenres:
    insertGenres(genre_id[counter], genre_name[counter])
    counter += 1

1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed

<h1>Genre Serie Mapping</h1>

In [4]:
def insertSeriesGenres(insert_series_id, insert_genres_id):
    try:
        connection = mysql.connector.connect(host='localhost',
                                             database='uniprojekt',
                                             user='root',
                                             password='')
        cursor = connection.cursor()
        
        mySql_insert_query = """INSERT INTO series_genres (series_id, genres_id) 
                                VALUES 
                                (%s, %s) """
        
        recordTuple = (insert_series_id, insert_genres_id)
        
        
        cursor.execute(mySql_insert_query, recordTuple)
        connection.commit()
        print(cursor.rowcount, "Record inserted successfully into SeriesGenres table")
        cursor.close()

    except mysql.connector.Error as error:
        print("Failed to insert record into SeriesGenres table {}".format(error))

    finally:
        if (connection.is_connected()):
            connection.close()
            print("MySQL connection is closed")

<h1>Serien Definition</h1>

In [5]:
def insertSeries(insert_id, insert_name, insert_original_language, insert_overview, insert_image_path):
    try:
        connection = mysql.connector.connect(host='localhost',
                                             database='uniprojekt',
                                             user='root',
                                             password='')
        cursor = connection.cursor()
        
        mySql_insert_query = """INSERT INTO Series (ID, Name, Original_Language, Overview, Image_Path) 
                                VALUES 
                                (%s, %s, %s, %s, %s) """
        
        recordTuple = (insert_id, insert_name, insert_original_language, insert_overview, insert_image_path)
        
        
        cursor.execute(mySql_insert_query, recordTuple)
        connection.commit()
        print(cursor.rowcount, "Record inserted successfully into Series table")
        cursor.close()

    except mysql.connector.Error as error:
        print("Failed to insert record into Series table {}".format(error))

    finally:
        if (connection.is_connected()):
            connection.close()
            print("MySQL connection is closed")

<h1>Serien und Seriengenre einfügen

In [6]:
page_counter = 1

while page_counter <= 5:
    print("page: "+str(page_counter))
    response = requests.get("https://api.themoviedb.org/3/tv/popular?api_key=6896b525add50bf2605cbd1ecb2d95c9&language=de&page="+str(page_counter))
    series = response.json()['results']
    
    series_id = []
    series_name = []
    series_original_language = []
    series_overview = []
    series_image = []
    series_genres = []
    
    for line in series:
        series_id.append(line['id'])
        series_name.append(line['name'])
        series_original_language.append(line['original_language'])
        series_overview.append(line['overview'])
        series_image.append("https://image.tmdb.org/t/p/w185"+str(line['poster_path']))
        series_genres.append(line['genre_ids'])

    countOfSeries = len(series_id)
    
    counter = 0
    while counter < countOfSeries:
        if series_image[counter] == "https://image.tmdb.org/t/p/w185None":
            print("Serie skipped, kein Bild")
        else:
            insertSeries(series_id[counter], series_name[counter], series_original_language[counter], series_overview[counter], series_image[counter])
            for series_line in series_genres[counter]:
                insertSeriesGenres(series_id[counter], series_line)
        counter += 1
    
    page_counter += 1

page: 1
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
Failed to insert record into SeriesGenres table 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`uniprojekt`.`series_genres`, CONSTRAINT `genres_id` FOREIGN KEY (`genres_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE)
MySQL connection is closed
Failed to insert record into SeriesGenres table 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`uniprojekt`.`series_genres`, CONSTRAINT `genres_id` FOREIGN KEY (`genres_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE)
MySQL connection is closed
Failed to insert record into SeriesGenres table 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`uniprojekt`.`series_genres`, CONSTRAINT `genres_id` FOREIGN KEY (`genres_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE)
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
page: 2
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table

MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
page: 3
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
Failed to insert record into SeriesGenres table 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`uniprojekt`.`series_genres`, CONSTRAINT `genres_id` FOREIGN KEY (`genres_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE)
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
page: 4

1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
Failed to insert record into SeriesGenres table 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`uniprojekt`.`series_genres`, CONSTRAINT `genres_id` FOREIGN KEY (`genres_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE)
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
page: 5
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
Failed to insert record into SeriesGenres table 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`uniprojekt`.`series_genres`, CONSTRAINT `genres_id` FOREIGN KEY (`genres_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE)
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table

MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
Failed to insert record into SeriesGenres table 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`uniprojekt`.`series_genres`, CONSTRAINT `genres_id` FOREIGN KEY (`genres_id`) REFERENCES `genres` (`id`) ON DELETE CASCADE)
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into Series table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed
1 Record inserted successfully into SeriesGenres table
MySQL connection is closed